import json

# Game board is always 3x4 with 2 blank squares

CARDS = {
    "level_1": {
          "1": "rog o_p b_o gpo",
          "2": "rog o_p b_b gpr",
          "3": "gg_ oo_ rrb ppb",
          "4": "bob __r obb rgg",
          "5": "bob __r gbb bgg",
          "6": "rrb __r gbb bgg",
          "7": "rgo p__ rbr gop",
          "8": "pog r__ gbr pgb",
          "9": "bog p__ gbg prb",
         "10": "rrg __g gbg prb",
         "11": "rrb __p pbg orb",
         "12": "gpo g_r p_p pbo",
         "13": "rgo o_o r_g bgp",
         "14": "gob __p pbg orb",
         "15": "gpo g_r p_p pbo",
         "16": "rgo o_o r_g bgp",
         "17": "gob __p pbg orb",
         "18": "ggr p_r p_b oob",
         "19": "ggr o_r o_b ppb",
         "20": "rrb p_b p_g oog",
         "21": "bpp boo __o rpg",
         "22": "pbp gbo __r gbr",
         "23": "ror ppo o__ goo",
         "24": "prp oro __o gbg",
         "25": "bpp oro __o gbg",
         "26": "pbp __o ppp oog",
         "27": "ror ppg g__ poo",
         "28": "gpo p_o p_g ror"
    },
    "level_2": {
         "29": "bgo bgr obp __g",
         "30": "obr pgg obo __r",
         "31": "obr rop obg __g",
         "32": "ggg brg gog b__",
         "33": "ror gbp brr g__",
         "34": "ggg brg rog b__",
         "35": "prg gpb rob p__",
         "36": "grg rpg o__ bgb",
         "37": "pro pgr pop __p",
         "38": "ppr bgb _pp _ob",
         "39": "prg pgg pop __p",
         "40": "prg pgg pog __b",
         "41": "prg rrg rgg __b",
         "42": "rpr orr prg r__",
         "43": "opr brr prg r__",
         "44": "ooo brr pgp r__",
         "45": "prb prr bgp p__",
         "46": "gbo pgr pop __p",
         "47": "__r boo bog ppo",
         "48": "prg pgg pop __p",
         "49": "g__ rrp rbg rbg",
         "50": "oog rrg bbo __b",
         "51": "__g bog bor ppr",
         "52": "rpo rrr bbo __b",
         "53": "__b rop gor ppr",
         "54": "bg_ bg_ ppg rop"
    },
    "level_3": {
         "55": "ro_ pro bbb ob_",
         "56": "_pr _pg rog bpp",
         "57": "_rb bgr oro _gb",
         "58": "_ro rpr rbo _bb",
         "59": "gb_ gg_ opp ogg",
         "60": "gp_ op_ ppp brr",
         "61": "oo_ pr_ ppo gpo",
         "62": "oo_ pr_ ppp gpr",
         "63": "bo_ br_ bop gpr",
         "64": "gp_ rb_ bob gpg",
         "65": "gp_ rb_ obb bog",
         "66": "_gp _rb oob obo",
         "67": "_rp _gp oob obo",
         "68": "_pb _gp gob bbo",
         "69": "_rr rob gop pp_",
         "70": "pr_ rr_ pob ggo",
         "71": "pr_ pg_ pob pro",
         "72": "_ro gpr obo _bb",
         "73": "_pr gro oob _bb",
         "74": "_ro _ob opg opg",
         "75": "op_ ogo ogg _gb",
         "76": "_pr gro obo _bb",
         "77": "rp_ gp_ rog prp",
         "78": "ro_ pr_ bbg obo",
         "79": "pr_ ro_ rrb goo"
    },
    "level_4": {
         "80": "rb_ ppb gog pp_",
         "81": "po_ pb_ brg bpb",
         "82": "_oo _rg ogb bbp",
         "83": "po_ pb_ brr bpp",
         "84": "rb_ ppo rgg pp_",
         "85": "bg_ orp ogg rr_",
         "86": "oo_ bg_ brr bpp",
         "87": "_gr ogb rro _bg",
         "88": "oo_ bg_ brr bpp",
         "89": "_bp roo ogb _go",
         "90": "_or gbo pop _rp",
         "91": "oo_ bg_ grg ppg",
         "92": "pg_ pp_ bgg bgb",
         "93": "pg_ gp_ ggg bgb",
         "94": "pg_ gp_ ggg gbb",
         "95": "pg_ ppp bgr bg_",
         "96": "pg_ brp opg _pr",
         "97": "pg_ ppp bgr _or",
         "98": "og_ bpb gpg _oo",
         "99": "pg_ pgg rrb _gb",
        "100": "pg_ pgb brr _ro",
        "101": "pg_ rpo ooo _ob",
        "102": "rr_ ppp ror ob_",
        "103": "_pr _ro prr ggo"
    }
}
